# Generated by Django 5.0.7 on 2024-09-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
