# Generated by Django 5.0.6 on 2024-09-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_appointment_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/reports'),
        ),
    ]
