# Generated by Django 5.0.6 on 2024-09-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='completed',
        ),
    ]
