# Generated by Django 5.0.6 on 2024-09-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_appointment_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
