# Generated by Django 5.0.6 on 2024-09-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_appointment_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='review',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
