# Generated by Django 5.0.6 on 2024-09-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_doctor_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rating',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
